name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build: [ Linux, macOS ]
        include:
          - build: Linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
          - build: macOS
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
    steps:
      - name: Install dependencies (for Linux)
        run: |
          sudo apt-get install zsh
          sudo apt-add-repository ppa:fish-shell/release-3
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install fish
          python3 -V
          tmux -V
          locale
        if: runner.os == 'Linux'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
      - name: Install dependencies (for macOS)
        run: |
          brew install tmux
          brew install zsh
          brew install fish
          python3 -V
          tmux -V
          locale
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install correct toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: make test
        env:
          LC_ALL: en_US.UTF-8
          TERM: xterm-256color
      - name: Cache
        uses: Swatinem/rust-cache@v1
